In [64]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
import numpy as np

In [65]:
sent=[ 'the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your video are good',
      ]

In [66]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your video are good']

In [67]:
# Define vocabulary size
voc_size = 10000

In [68]:
# One Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr # given the index of the vectors 

[[1087, 7019, 3621, 1992],
 [1087, 7019, 3621, 4204],
 [1087, 6212, 3621, 8583],
 [7776, 5859, 2857, 5446, 7019],
 [7776, 5859, 2857, 5446, 2350],
 [6655, 1087, 3804, 3621, 9548],
 [5065, 3987, 2653, 5446]]

In [69]:
# Word emdedding repsentation 
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [70]:
import numpy as np

In [71]:
# We need to make all sentence are equal sizes other wise we not able to train model 
# Make all sentences equal sizes using padding
sent_length = 8  # Desired length of all sequences
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1087 7019 3621 1992]
 [   0    0    0    0 1087 7019 3621 4204]
 [   0    0    0    0 1087 6212 3621 8583]
 [   0    0    0 7776 5859 2857 5446 7019]
 [   0    0    0 7776 5859 2857 5446 2350]
 [   0    0    0 6655 1087 3804 3621 9548]
 [   0    0    0    0 5065 3987 2653 5446]]


In [72]:
# feature representation 
dim=10

In [73]:
# Build the model
model = Sequential()

# Add embedding layer
model.add(Embedding(voc_size, dim, input_length=sent_length))

# Compile the model
model.compile(optimizer='adam', loss='mse')

In [74]:
model.predict(embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step


array([[[-4.44281213e-02, -3.67916822e-02,  4.23336066e-02,
          3.97893526e-02, -7.38102198e-03, -3.46806534e-02,
         -1.96817163e-02, -2.14895960e-02,  9.93957371e-03,
         -2.35493183e-02],
        [-4.44281213e-02, -3.67916822e-02,  4.23336066e-02,
          3.97893526e-02, -7.38102198e-03, -3.46806534e-02,
         -1.96817163e-02, -2.14895960e-02,  9.93957371e-03,
         -2.35493183e-02],
        [-4.44281213e-02, -3.67916822e-02,  4.23336066e-02,
          3.97893526e-02, -7.38102198e-03, -3.46806534e-02,
         -1.96817163e-02, -2.14895960e-02,  9.93957371e-03,
         -2.35493183e-02],
        [-4.44281213e-02, -3.67916822e-02,  4.23336066e-02,
          3.97893526e-02, -7.38102198e-03, -3.46806534e-02,
         -1.96817163e-02, -2.14895960e-02,  9.93957371e-03,
         -2.35493183e-02],
        [-2.88265701e-02, -1.33477449e-02,  2.90793665e-02,
         -6.39317185e-03,  2.99998410e-02,  1.59737952e-02,
         -3.66312750e-02,  2.70079859e-02,  2.053953

In [75]:
embedded_docs[0]

array([   0,    0,    0,    0, 1087, 7019, 3621, 1992])

In [76]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


array([[[-4.44281213e-02, -3.67916822e-02,  4.23336066e-02,
          3.97893526e-02, -7.38102198e-03, -3.46806534e-02,
         -1.96817163e-02, -2.14895960e-02,  9.93957371e-03,
         -2.35493183e-02],
        [-4.44281213e-02, -3.67916822e-02,  4.23336066e-02,
          3.97893526e-02, -7.38102198e-03, -3.46806534e-02,
         -1.96817163e-02, -2.14895960e-02,  9.93957371e-03,
         -2.35493183e-02],
        [-4.44281213e-02, -3.67916822e-02,  4.23336066e-02,
          3.97893526e-02, -7.38102198e-03, -3.46806534e-02,
         -1.96817163e-02, -2.14895960e-02,  9.93957371e-03,
         -2.35493183e-02],
        [-4.44281213e-02, -3.67916822e-02,  4.23336066e-02,
          3.97893526e-02, -7.38102198e-03, -3.46806534e-02,
         -1.96817163e-02, -2.14895960e-02,  9.93957371e-03,
         -2.35493183e-02],
        [-2.88265701e-02, -1.33477449e-02,  2.90793665e-02,
         -6.39317185e-03,  2.99998410e-02,  1.59737952e-02,
         -3.66312750e-02,  2.70079859e-02,  2.053953