# About Dataset
### Context
This is a small subset of dataset of Book reviews from Amazon Kindle Store category.

### Content
5 core dataset of product reviews from Amazon Kindle Store category from May 1996 - July 2014. Contains total of 982619 entries. Each reviewer has at least 5 reviews and each product has at least 5 reviews in this dataset.
##### Columns

- asin - ID of the product, like B000FA64PK
- helpful - helpfulness rating of the review - example: 2/3.
- overall - rating of the product.
- reviewText - text of the review (heading).
- reviewTime - time of the review (raw).
- reviewerID - ID of the reviewer, like A3SPTOKDG7WBLN
- reviewerName - name of the reviewer.
- summary - summary of the review (description).
- unixReviewTime - unix timestamp.
##### Which file to use?
There are two files one is preprocessed ready for sentiment analysis and other is unprocessed to you basically have to process the dataset and then perform sentiment analysis

#### Acknowledgements
This dataset is taken from Amazon product data, Julian McAuley, UCSD website. http://jmcauley.ucsd.edu/data/amazon/

License to the data files belong to them.

#### Inspiration
- Sentiment analysis on reviews.
- Understanding how people rate usefulness of a review/ What factors influence helpfulness of a review.
- Fake reviews/ outliers.
- Best rated product IDs, or similarity between products based on reviews alone (not the best idea ikr).
- Any other interesting analysis

#### Best Practices 
- 1 Preprocessing And Cleaning 
- 2 Train Test Split 
- 3 BoW and Word2Vec 
- 4 Train ML Model 

In [1]:
import pandas as pd
data = pd.read_csv('Kindle Book Review Sentiment Analysis.csv')

In [2]:
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [3]:
data.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'asin', 'helpful', 'rating', 'reviewText',
       'reviewTime', 'reviewerID', 'reviewerName', 'summary',
       'unixReviewTime'],
      dtype='object')

In [4]:
df=data[['reviewText','rating']]

In [5]:
df.shape

(12000, 2)

In [6]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [7]:
df['rating'].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [8]:
df['rating'].value_counts()

5    3000
4    3000
3    2000
2    2000
1    2000
Name: rating, dtype: int64

In [9]:
# Cleaning and Preprocessing 

In [10]:
# Positive review is 1 and negative review is o 
df['rating']= df['rating'].apply (lambda x:0 if x<3 else 1)

C:\Users\bhimr\AppData\Local\Temp\ipykernel_7624\3620898277.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating']= df['rating'].apply (lambda x:0 if x<3 else 1)


In [11]:
df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       1
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       1
3  Aggie is Angela Lansbury who carries pocketboo...       1
4  I did not expect this type of book to be in li...       1

In [12]:
df['rating'].value_counts()

1    8000
0    4000
Name: rating, dtype: int64

In [13]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\bhimr\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\bhimr\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [14]:
## 1 Lower all the cases 
df['reviewText'] = df['reviewText'].str.lower()

C:\Users\bhimr\AppData\Local\Temp\ipykernel_7624\2692524294.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].str.lower()


In [15]:
df.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [16]:
## Removing Special Charectors 
df['reviewText']=df['reviewText'].apply( lambda x:re.sub('[^a-z A-z 0-9]+','',x))

C:\Users\bhimr\AppData\Local\Temp\ipykernel_7624\3906477127.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply( lambda x:re.sub('[^a-z A-z 0-9]+','',x))


In [17]:
## Removing the Stopwords 
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))

C:\Users\bhimr\AppData\Local\Temp\ipykernel_7624\1306999428.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))


In [18]:
## Remove Url
df['reviewText']=df['reviewText'].apply ( lambda x: re.sub(r'(http|https|ftp|shh)://([\w_-]+(?:\.[\w_-]+))([\w.,@?^=%&:/~+#-])?','',str(x)))

C:\Users\bhimr\AppData\Local\Temp\ipykernel_7624\2238133283.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply ( lambda x: re.sub(r'(http|https|ftp|shh)://([\w_-]+(?:\.[\w_-]+))([\w.,@?^=%&:/~+#-])?','',str(x)))


In [19]:
## Removing html tags
!pip install beautifulsoup4
from bs4 import BeautifulSoup
df['reviewText']= df['reviewText'] .apply ( lambda x: BeautifulSoup(x, 'lxml').get_text())

C:\Users\bhimr\AppData\Local\Temp\ipykernel_7624\3602158222.py:4: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  df['reviewText']= df['reviewText'] .apply ( lambda x: BeautifulSoup(x, 'lxml').get_text())
C:\Users\bhimr\AppData\Local\Temp\ipykernel_7624\3602158222.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']= df['reviewText'] .apply ( lambda x: BeautifulSoup(x, 'lxml').get_text())


In [20]:
## Removing any additional spaces 
df['reviewText']=df['reviewText']. apply ( lambda x:" ".join(x.split()))

C:\Users\bhimr\AppData\Local\Temp\ipykernel_7624\4138817123.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText']. apply ( lambda x:" ".join(x.split()))


In [21]:
df.head()

reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [28]:
## Lemmatizer 
from nltk.stem import WordNetLemmatizer

# Initialize the lemmatizer
lemmatizer = WordNetLemmatizer()

# Define the lemmatization function
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

# Apply the function to the 'reviewText' column
df['reviewText'] = df['reviewText'].apply(lambda x: lemmatize_words(x))

C:\Users\bhimr\AppData\Local\Temp\ipykernel_7624\3642223258.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x: lemmatize_words(x))


In [29]:
df.head()

reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [31]:
## Train Test Split 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],
                                               test_size=0.25,random_state=0)

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

In [41]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow, y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf, y_train)

In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [45]:
y_pred_bow=nb_model_bow.predict(X_test_bow)

In [46]:
y_pred_tfidf=nb_model_tfidf.predict(X_test_tfidf)

In [50]:
# Classification Report
class_report = classification_report(y_test, y_pred_bow)
print("Classification Report:\n", class_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.42      0.67      0.52       974
           1       0.78      0.56      0.65      2026

    accuracy                           0.60      3000
   macro avg       0.60      0.62      0.59      3000
weighted avg       0.66      0.60      0.61      3000



In [51]:
confusion_matrix(y_test,y_pred_bow)

array([[ 654,  320],
       [ 891, 1135]], dtype=int64)

In [48]:
print("BOW accuracy:", accuracy_score(y_test, y_pred_bow))

BOW accuracy: 0.5963333333333334


In [49]:
print("TFIDF accuracy:", accuracy_score(y_test, y_pred_tfidf))

TFIDF accuracy: 0.5993333333333334


In [52]:
# Classification Report
class_report = classification_report(y_test, y_pred_tfidf)
print("Classification Report:\n", class_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.42      0.66      0.52       974
           1       0.78      0.57      0.66      2026

    accuracy                           0.60      3000
   macro avg       0.60      0.61      0.59      3000
weighted avg       0.66      0.60      0.61      3000



In [53]:
confusion_matrix(y_test,y_pred_tfidf)

array([[ 639,  335],
       [ 867, 1159]], dtype=int64)

# Need to use Word2Vec for Better Performance 

In [63]:
import gensim
from gensim.models import Word2Vec
import numpy as np
from tqdm import tqdm
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

In [64]:
# Step 1: Tokenize the sentences
X_train_tokens = [sentence.split() for sentence in X_train]
X_test_tokens = [sentence.split() for sentence in X_test]

In [65]:
# Step 2: Train Word2Vec model (adjust parameters if needed)
word2vec_model = Word2Vec(sentences=X_train_tokens, vector_size=100, window=5, min_count=1, workers=4)


In [66]:
# Step 3: Create a function to convert sentences into vectors by averaging the word vectors
def sentence_vectorizer(sentence, model):
    vector_size = model.vector_size
    words = [word for word in sentence if word in model.wv.index_to_key]
    if len(words) == 0:  # Handle case where none of the words are in the vocabulary
        return np.zeros(vector_size)
    word_vectors = [model.wv[word] for word in words]
    return np.mean(word_vectors, axis=0)

In [67]:
# Step 4: Convert the entire dataset into word vector representations
X_train_word2vec = np.array([sentence_vectorizer(sentence, word2vec_model) for sentence in tqdm(X_train_tokens)])
X_test_word2vec = np.array([sentence_vectorizer(sentence, word2vec_model) for sentence in tqdm(X_test_tokens)])

100%|█████████████████████████████████████████████████████████████████████████████| 3000/3000 [00:29<00:00, 102.80it/s]


In [68]:
# Step 5: Train a classifier (Random Forest in this case)
classifier = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
classifier.fit(X_train_word2vec, y_train)

RandomForestClassifier(max_depth=10, random_state=42)

In [69]:
# Step 6: Make predictions
y_pred = classifier.predict(X_test_word2vec)

In [70]:
# Step 7: Evaluate the model

# 7a: Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# 7b: Classification Report
print("Classification Report:\n", classification_report(y_test, y_pred))

# 7c: Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.7483333333333333
Classification Report:
               precision    recall  f1-score   support

           0       0.66      0.47      0.55       974
           1       0.78      0.88      0.83      2026

    accuracy                           0.75      3000
   macro avg       0.72      0.68      0.69      3000
weighted avg       0.74      0.75      0.74      3000

Confusion Matrix:
 [[ 459  515]
 [ 240 1786]]


## Lets check other models 

In [75]:
!pip install xgboost

In [78]:
import xgboost as xgb
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import seaborn as sns

In [79]:
# Step 1: Initialize the XGBoost classifier
xgb_classifier = xgb.XGBClassifier(objective='binary:logistic', max_depth=5, learning_rate=0.1, n_estimators=100, random_state=42)

In [80]:
# Step 2: Train the classifier
xgb_classifier.fit(X_train_word2vec, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, random_state=42, ...)

In [81]:
# Step 3: Make predictions
y_pred_xgb = xgb_classifier.predict(X_test_word2vec)

In [82]:
# Step 4: Evaluate the model
# 4a: Accuracy
accuracy = accuracy_score(y_test, y_pred_xgb)
print("XGBoost Accuracy:", accuracy)
# 4b: Classification Report
print("XGBoost Classification Report:\n", classification_report(y_test, y_pred_xgb))
# 4c: Confusion Matrix
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
print("XGBoost Confusion Matrix:\n", conf_matrix_xgb)

XGBoost Accuracy: 0.7516666666666667
XGBoost Classification Report:
               precision    recall  f1-score   support

           0       0.64      0.55      0.59       974
           1       0.80      0.85      0.82      2026

    accuracy                           0.75      3000
   macro avg       0.72      0.70      0.71      3000
weighted avg       0.74      0.75      0.75      3000

XGBoost Confusion Matrix:
 [[ 533  441]
 [ 304 1722]]


# Hyperparameter tuning for the both model rf and xgb 

In [83]:
rf_params = { "max_depth":[5, 7,15,10, None],
             "max_features":[5,7,"auto",8],
             "min_samples_split":[2,8,15,20],
             "n_estimators":[100,200,500,1000]}


Xgb_params = {
    "learning_rate":[0.1,0.01],
    "max_depth":[5,8,12,20,30],
    "n_stimators":[100,200,300],
    "colsample_bytree":[0.3,0.4,0.5,0.8,1]
}

In [84]:
randomcv_models = [
                ("RF",RandomForestClassifier(), rf_params),
    ("Xgb Boost",XGBClassifier(), Xgb_params)
    
]

In [85]:
randomcv_models

[('RF',
  RandomForestClassifier(),
  {'max_depth': [5, 7, 15, 10, None],
   'max_features': [5, 7, 'auto', 8],
   'min_samples_split': [2, 8, 15, 20],
   'n_estimators': [100, 200, 500, 1000]}),
 ('Xgb Boost',
  XGBClassifier(base_score=None, booster=None, callbacks=None,
                colsample_bylevel=None, colsample_bynode=None,
                colsample_bytree=None, device=None, early_stopping_rounds=None,
                enable_categorical=False, eval_metric=None, feature_types=None,
                gamma=None, grow_policy=None, importance_type=None,
                interaction_constraints=None, learning_rate=None, max_bin=None,
                max_cat_threshold=None, max_cat_to_onehot=None,
                max_delta_step=None, max_depth=None, max_leaves=None,
                min_child_weight=None, missing=nan, monotone_constraints=None,
                multi_strategy=None, n_estimators=None, n_jobs=None,
                num_parallel_tree=None, random_state=None, ...),
  {'lear

In [87]:
from sklearn.model_selection import RandomizedSearchCV
model_param = {}
for name, model, params in randomcv_models:
    random =RandomizedSearchCV(estimator=model,
                               param_distributions=params,
                               n_iter=100,
                               cv=3,
                               verbose=2,
                               n_jobs=-1)

    random.fit(X_train_word2vec, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"--------------------Best Param for {model_name}---------------------------")
    print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits


C:\Users\bhimr\Documents\Downloads\Lib\site-packages\sklearn\ensemble\_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


Fitting 3 folds for each of 100 candidates, totalling 300 fits


C:\Users\bhimr\Documents\Downloads\Lib\site-packages\xgboost\core.py:160: UserWarning: [02:05:30] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "n_stimators" } are not used.

  warnings.warn(smsg, UserWarning)


--------------------Best Param for RF---------------------------
{'n_estimators': 1000, 'min_samples_split': 8, 'max_features': 'auto', 'max_depth': None}
--------------------Best Param for Xgb Boost---------------------------
{'n_stimators': 300, 'max_depth': 20, 'learning_rate': 0.1, 'colsample_bytree': 0.4}


In [88]:
# Define models
models = {
    
    "Random Forest": RandomForestClassifier(n_estimators=200,min_samples_split=2,max_features=8,
                                           max_depth= None),
    "Xgb Boost ": XGBClassifier(n_stimators= 200, max_depth= 30, learning_rate= 0.1, colsample_bytree= 1)
}

In [90]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score

# Iterate over models
for name, model in models.items():
    # Fit the model
    model.fit(X_train_word2vec, y_train)

    # Make predictions
    y_train_pred = model.predict(X_train_word2vec)
    y_test_pred = model.predict(X_test_word2vec)

    # Training set performance (use y_train, not X_train_word2vec)
    model_train_accuracy = accuracy_score(y_train, y_train_pred)
    model_train_f1 = f1_score(y_train, y_train_pred, average='weighted')
    model_train_precision = precision_score(y_train, y_train_pred)
    model_train_recall = recall_score(y_train, y_train_pred)
    model_train_rocauc_score = roc_auc_score(y_train, y_train_pred)

    # Testing set performance (use y_test, not X_test_word2vec)
    model_test_accuracy = accuracy_score(y_test, y_test_pred)
    model_test_f1 = f1_score(y_test, y_test_pred, average='weighted')
    model_test_precision = precision_score(y_test, y_test_pred)
    model_test_recall = recall_score(y_test, y_test_pred)
    model_test_rocauc_score = roc_auc_score(y_test, y_test_pred)

    # Print model name
    print(f"Model: {name}")

    # Print evaluation metrics for training set
    print("Training Set Performance:")
    print("Accuracy:", model_train_accuracy)
    print("F1 Score:", model_train_f1)
    print("Precision:", model_train_precision)
    print("Recall:", model_train_recall)
    print("ROC AUC Score:", model_train_rocauc_score)
    print("==============================================================")

    # Print evaluation metrics for testing set
    print("\nTesting Set Performance:")
    print("Accuracy:", model_test_accuracy)
    print("F1 Score:", model_test_f1)
    print("Precision:", model_test_precision)
    print("Recall:", model_test_recall)
    print("ROC AUC Score:", model_test_rocauc_score)
    print("==============================================================\n")


Model: Random Forest
Training Set Performance:
Accuracy: 1.0
F1 Score: 1.0
Precision: 1.0
Recall: 1.0
ROC AUC Score: 1.0

Testing Set Performance:
Accuracy: 0.7513333333333333
F1 Score: 0.740926206736733
Precision: 0.7826855123674912
Recall: 0.8746298124383021
ROC AUC Score: 0.6847481711062147



C:\Users\bhimr\Documents\Downloads\Lib\site-packages\xgboost\core.py:160: UserWarning: [02:09:02] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "n_stimators" } are not used.

  warnings.warn(smsg, UserWarning)


Model: Xgb Boost 
Training Set Performance:
Accuracy: 1.0
F1 Score: 1.0
Precision: 1.0
Recall: 1.0
ROC AUC Score: 1.0

Testing Set Performance:
Accuracy: 0.7526666666666667
F1 Score: 0.7462035742498255
Precision: 0.793418647166362
Recall: 0.8568608094768015
ROC AUC Score: 0.6963975505289551

